/**
 * CineGrade Cinematic Presets
 *
 * Each preset is optimized for Apple Log (iPhone 15 Pro Max) footage
 * and emulates different cinematic film looks.
 */

const CINEMATIC_PRESETS = [
    {
        name: 'Rec.709',
        description: 'Standard LOG → Rec.709 conversion. Clean, neutral.',
        params: {
            exposure: 0,
            contrast: 1.1,
            highlights: -0.05,
            shadows: 0.05,
            temperature: 0,
            tint: 0,
            saturation: 1.05,
            vibrance: 0.1,
            liftR: 0, liftG: 0, liftB: 0,
            gammaR: 0, gammaG: 0, gammaB: 0,
            gainR: 1, gainG: 1, gainB: 1,
            grain: 0,
            vignette: 0,
            halation: 0,
            fade: 0,
            sharpen: 0.3,
        }
    },
    {
        name: 'Cine Warm',
        description: 'Look cinematográfico cálido. Tonos dorados, sombras ricas.',
        params: {
            exposure: 0.2,
            contrast: 1.25,
            highlights: -0.15,
            shadows: 0.1,
            temperature: 0.2,
            tint: 0.02,
            saturation: 0.95,
            vibrance: 0.15,
            liftR: 0.01, liftG: 0.005, liftB: -0.02,
            gammaR: 0.02, gammaG: 0.01, gammaB: -0.01,
            gainR: 1.05, gainG: 1.0, gainB: 0.92,
            grain: 0.02,
            vignette: 0.25,
            halation: 0.15,
            fade: 0.01,
            sharpen: 0.4,
        }
    },
    {
        name: 'Teal & Orange',
        description: 'El look Hollywood clásico. Sombras azuladas, tonos de piel cálidos.',
        params: {
            exposure: 0.15,
            contrast: 1.3,
            highlights: -0.1,
            shadows: 0.05,
            temperature: 0.1,
            tint: -0.02,
            saturation: 1.1,
            vibrance: 0.2,
            liftR: -0.02, liftG: 0.01, liftB: 0.05,
            gammaR: 0.03, gammaG: 0.0, gammaB: -0.02,
            gainR: 1.08, gainG: 0.98, gainB: 0.9,
            grain: 0.015,
            vignette: 0.3,
            halation: 0.1,
            fade: 0.005,
            sharpen: 0.35,
        }
    },
    {
        name: 'Deakins',
        description: 'Inspirado en Roger Deakins. Natural, limpio, elegante.',
        params: {
            exposure: 0.1,
            contrast: 1.2,
            highlights: -0.2,
            shadows: 0.08,
            temperature: 0.05,
            tint: 0,
            saturation: 0.9,
            vibrance: 0.1,
            liftR: 0.0, liftG: 0.0, liftB: 0.01,
            gammaR: 0.0, gammaG: 0.0, gammaB: 0.0,
            gainR: 1.0, gainG: 1.0, gainB: 0.98,
            grain: 0.01,
            vignette: 0.15,
            halation: 0.05,
            fade: 0.005,
            sharpen: 0.3,
        }
    },
    {
        name: 'Kodak 2383',
        description: 'Emulación del print stock Kodak 2383. Cálido, saturado.',
        params: {
            exposure: 0.15,
            contrast: 1.35,
            highlights: -0.12,
            shadows: 0.12,
            temperature: 0.12,
            tint: 0.02,
            saturation: 1.15,
            vibrance: 0.15,
            liftR: 0.02, liftG: 0.0, liftB: -0.02,
            gammaR: 0.01, gammaG: 0.005, gammaB: -0.01,
            gainR: 1.05, gainG: 1.0, gainB: 0.93,
            grain: 0.025,
            vignette: 0.2,
            halation: 0.2,
            fade: 0.01,
            sharpen: 0.25,
        }
    },
    {
        name: 'Fuji 3510',
        description: 'Emulación Fuji. Tonos fríos, greens limpios, sombras suaves.',
        params: {
            exposure: 0.1,
            contrast: 1.2,
            highlights: -0.1,
            shadows: 0.06,
            temperature: -0.08,
            tint: 0.03,
            saturation: 0.95,
            vibrance: 0.12,
            liftR: -0.01, liftG: 0.01, liftB: 0.02,
            gammaR: 0.0, gammaG: 0.01, gammaB: 0.01,
            gainR: 0.97, gainG: 1.02, gainB: 1.03,
            grain: 0.02,
            vignette: 0.15,
            halation: 0.08,
            fade: 0.008,
            sharpen: 0.3,
        }
    },
    {
        name: 'Blade Runner',
        description: 'Sci-fi noir. Alto contraste, tonos neón, sombras profundas.',
        params: {
            exposure: -0.05,
            contrast: 1.45,
            highlights: -0.05,
            shadows: -0.1,
            temperature: -0.1,
            tint: -0.05,
            saturation: 1.2,
            vibrance: 0.25,
            liftR: -0.02, liftG: -0.01, liftB: 0.04,
            gammaR: 0.0, gammaG: -0.02, gammaB: 0.02,
            gainR: 0.95, gainG: 0.95, gainB: 1.1,
            grain: 0.03,
            vignette: 0.45,
            halation: 0.2,
            fade: 0.0,
            sharpen: 0.5,
        }
    },
    {
        name: 'Vintage 70s',
        description: 'Film descolorido de los 70s. Fade, tonos pastel, grano.',
        params: {
            exposure: 0.2,
            contrast: 1.05,
            highlights: -0.2,
            shadows: 0.15,
            temperature: 0.15,
            tint: 0.05,
            saturation: 0.75,
            vibrance: 0.05,
            liftR: 0.04, liftG: 0.03, liftB: 0.01,
            gammaR: 0.02, gammaG: 0.01, gammaB: -0.01,
            gainR: 1.02, gainG: 0.98, gainB: 0.92,
            grain: 0.06,
            vignette: 0.35,
            halation: 0.3,
            fade: 0.06,
            sharpen: 0.1,
        }
    },
    {
        name: 'Noir',
        description: 'Film noir moderno. Desaturado, alto contraste, misterioso.',
        params: {
            exposure: 0.0,
            contrast: 1.5,
            highlights: -0.1,
            shadows: -0.05,
            temperature: -0.05,
            tint: 0,
            saturation: 0.2,
            vibrance: 0.0,
            liftR: 0.0, liftG: 0.0, liftB: 0.02,
            gammaR: 0.0, gammaG: 0.0, gammaB: 0.0,
            gainR: 1.0, gainG: 1.0, gainB: 1.0,
            grain: 0.04,
            vignette: 0.5,
            halation: 0.0,
            fade: 0.01,
            sharpen: 0.6,
        }
    },
    {
        name: 'Wes Anderson',
        description: 'Colores pastel, simetría visual, estética de cuento.',
        params: {
            exposure: 0.25,
            contrast: 1.15,
            highlights: -0.15,
            shadows: 0.12,
            temperature: 0.08,
            tint: 0.02,
            saturation: 1.25,
            vibrance: 0.2,
            liftR: 0.02, liftG: 0.02, liftB: 0.0,
            gammaR: 0.01, gammaG: 0.01, gammaB: -0.01,
            gainR: 1.03, gainG: 1.0, gainB: 0.95,
            grain: 0.015,
            vignette: 0.1,
            halation: 0.1,
            fade: 0.02,
            sharpen: 0.35,
        }
    },
    {
        name: 'Moonlight',
        description: 'Tonos fríos, sombras azuladas, atmósfera nocturna íntima.',
        params: {
            exposure: -0.1,
            contrast: 1.2,
            highlights: -0.15,
            shadows: 0.05,
            temperature: -0.2,
            tint: -0.05,
            saturation: 0.85,
            vibrance: 0.1,
            liftR: -0.02, liftG: 0.0, liftB: 0.04,
            gammaR: -0.01, gammaG: 0.0, gammaB: 0.02,
            gainR: 0.95, gainG: 0.98, gainB: 1.06,
            grain: 0.02,
            vignette: 0.3,
            halation: 0.05,
            fade: 0.01,
            sharpen: 0.25,
        }
    },
    {
        name: 'Dune',
        description: 'Desértico, dorado, épico. Inspirado en Villeneuve/Fraser.',
        params: {
            exposure: 0.3,
            contrast: 1.3,
            highlights: -0.1,
            shadows: 0.05,
            temperature: 0.3,
            tint: 0.05,
            saturation: 0.8,
            vibrance: 0.1,
            liftR: 0.03, liftG: 0.02, liftB: -0.03,
            gammaR: 0.03, gammaG: 0.01, gammaB: -0.02,
            gainR: 1.1, gainG: 1.0, gainB: 0.85,
            grain: 0.025,
            vignette: 0.2,
            halation: 0.25,
            fade: 0.015,
            sharpen: 0.4,
        }
    },
];
